server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: $2a$10$3py3atqf.uu6Dvect9SrFOeyHBolijzp8Yb7E51e6zwzk4seVTJeK
      roles: USER

